apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: manual-schedule
  name: manual-schedule
spec:
  # make sure the stop Temporarily the kube-scheduler for this pod to be taking place on the master
  # just mv the kube-scheduler file (mv /etc/kubernetes/manifests/kube-scheduler.yaml ~/) this will stop it, put it back to get it to working again
  nodeName: cluster2-master1 
  containers:
  - image: httpd:2.4-alpine
    name: manual-schedule
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
