apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-app
          image: nginx:1.30.4
          command:
            - /bin/sh
            - -c
            - |
              hostname > /tmp/hostname-container
              nginx -g 'daemon off;'
