apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: nginx
          command:
            - /bin/sh
            - -c
            - |
              hostname > /tmp/hostname-container
              nginx -g 'daemon off;'
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
